# Generated by Django 2.2.1 on 2019-05-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone',
            new_name='photo',
        ),
    ]
