# Generated by Django 2.2.1 on 2019-05-12 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190512_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 15, 32, 48, 112823, tzinfo=utc)),
        ),
    ]
