# Generated by Django 2.2.1 on 2019-05-14 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190514_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 9, 49, 59, 227848, tzinfo=utc)),
        ),
    ]
