# Generated by Django 2.2.1 on 2019-05-15 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20190514_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 8, 11, 24, 281727, tzinfo=utc)),
        ),
    ]
